name: Documentation

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --locked --dev

    - name: Build notebooks
      run: uv run --group examples jupytext --set-formats ipynb,md --execute docs/examples/*/*.md

    - name: Build docs
      run: uv run mkdocs build

    - name: Upload static files
      uses: actions/upload-pages-artifact@v3
      with:
        path: site/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4


